### ISSUE TITLE
[Feature Request] Multiple instance

### ISSUE THREAD

**Issue by raelschiffler** [WAClient/WALC#106]
Let us log into 2 accounts at the same time.

**Comment by Zzombiee2361** [comment]
There is already Allow Multiple Instances option, but I don't know if it works properly, have you tried that?

**Comment by Zzombiee2361** [comment]
I've been working on this, but it's incredibly difficult to implement. Not to mention I have to implement it for the new Whatsapp Multi Device. Also, designing new features around it slows down development a lot, and I barely have enough time to develop this project as it is. So I've decided to stop pursuing this.

**Comment by YoungFellow-le** [comment]
Agreed.
