### ISSUE TITLE
[Bug Report] Duplicated instance after closing to tray and trying to open it again

### ISSUE THREAD

**Issue by REIS0** [WAClient/WALC#147]
When walc is set to close to tray, if you try to open it again from an icon in my favorites bar or from the menu app instead of the icon tray, it will open another walc instance instead of showing the one already running.

Installed from snap store

**To Reproduce**
1. Open walc
2. Close to tray
3. Try to open it again from anything else than the icon tray
4. It will create another instance, instead of opening the one is already there

**Expected behavior**
Don't open another instance, open the one already in the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/38042161/118737254-f5b42980-b833-11eb-9707-53a78c3a1d90.png)

**System Information (please complete the following information):**
 - OS/Distro: Pop_OS! 20.04

**Comment by tubbadu** [comment]
this happens also with the appimage in kubuntu 21.04
