### ISSUE TITLE
Minimizing and reopening the Walc windows gives a screen garbage.

### ISSUE THREAD

**Issue by shorewall** [WAClient/WALC#148]
**Describe the bug**
Starting walc looks ok. But minimizing the window and reopening gives a window garbage
The old appimage worked fine.

**WALC Installation Type:** AppImage / Snap

walc 0.2.1 appimage

**To Reproduce**
Start Walc. Minimize the window then reopen/maximize.
The walc window contails garbage
**Expected behavior**
Have the right content once the windows is mazimized again.

**Did you try closing and then opening it back?:** Yes / No
yes
**Screenshots**

**System Information (please complete the following information):**
Mageia 6.1

**** Request **
Where can I download the previous appimage that worked for me?
**** Console log ****
[root@localhost Scaricati]# ./walc.AppImage --no-sandbox
Checking for update                                                   
                                                                                 
DevTools listening on ws://127.0.0.1:44313/devtools/browser/91e9dcd1-5b1d-492d-8cd0-dd3f1d78d8eb
(node:19380) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information                                 
(node:19380) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Creating whatsapp client
Update for version 0.2.1 is not available (latest version: 0.2.1, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
Whatsapp client ready
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Instance list:  [ 'walc' ]
Quiting instance:  walc
(node:19380) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /tmp/.mount_walc.A4p0leQ/resources/app.asar/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/tmp/.mount_walc.A4p0leQ/resources/app.asar/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ExecutionContext._evaluateInternal (/tmp/.mount_walc.A4p0leQ/resources/app.asar/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:201:50)
    at ExecutionContext.evaluateHandle (/tmp/.mount_walc.A4p0leQ/resources/app.asar/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:152:21)
    at WaitTask.rerun (/tmp/.mount_walc.A4p0leQ/resources/app.asar/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:532:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[root@localhost Scaricati]# 
![Walc_sarbage](https://user-images.githubusercontent.com/15981554/119981200-a3a29f00-bfbd-11eb-8a24-3f5e517179e6.png)

**Comment by Zzombiee2361** [comment]
Please try the new beta version to see if it's still happening https://github.com/WAClient/WALC/releases

I'll close this for now, let me know if the bug persists
