### ISSUE TITLE
[Bug Report] Duplicate tray icon after disable and enable icon

### ISSUE THREAD

**Issue by yalin** [WAClient/WALC#152]
**Describe the bug**

I'm using Ubuntu 20.04.
From the settings menu, I disable tray icon, then enable again. Previous icon turns into three dots and a new WALC icon appears on the left of the previous icon. It can be seen detailed in the screenshot

**WALC Installation Type:** AppImage / Snap
**Snap**

**To Reproduce**
1. Go to settings > tray icon
2. Click on "enable tray icon" to disable
3. Click on "enable tray icon" to enable again
4. See error on tray icon area.

**Expected behavior**

**Did you try closing and then opening it back?:** Yes / No
Yes

**Screenshots**
![image](https://user-images.githubusercontent.com/652545/120212935-36854880-c20d-11eb-9271-b068bf2b2a71.png)

**System Information (please complete the following information):**
 - OS/Distro:
 - Ubuntu 20.04

**Additional context**

**Comment by Zzombiee2361** [comment]
Please check if the issue still persist in the latest version

**Comment by yalin** [comment]
> Please check if the issue still persist in the latest version

It seems solved. Thank you.
