### ISSUE TITLE
No more tray badge notifications since last Whatsapp Update.

### ISSUE THREAD

**Issue by bkmo** [WAClient/WALC#157]
Getting audio and occasional popup notifications, but no tray badge numbers since the latest whatsapp update. Running 0.2.1 Appimage on Arch Linux KDE Plasma Desktop.

**Comment by YoungFellow-le** [comment]
I have the exact same issue on Linux Mint Cinnamon.

**Comment by hiddenman** [comment]
Confirms that, the same issue.

**Comment by hiddenman** [comment]
it seems that the npm package must be updated: https://github.com/pedroslopez/whatsapp-web.js/releases

**Comment by Zzombiee2361** [comment]
Please try the beta version and see if there's any issue
https://github.com/WAClient/WALC/releases

**Comment by bkmo** [comment]
running it now.......will report my findings at a later.  Thanks a bunch for the update.

**Comment by bkmo** [comment]
Seems to be fine...tray badge count is working again.

**Comment by Zzombiee2361** [comment]
@bkmo Any issues after using it for a week?

**Comment by bkmo** [comment]
Seems ok to me...no problems.

**Comment by bkmo** [comment]
Even this beta version does not present tray badge numbers anymore. It ceased to work about 10 days ago.

**Comment by Zzombiee2361** [comment]
> It ceased to work about 10 days ago.

That's exactly why I released a new update, to make sure whatsapp integration works. Is the dashboard icon at least still shown?

**Comment by bkmo** [comment]
I did not notice you updated yesterday. The only thing I was missing was the badges with the message count. I am now testing the update.

**Comment by bkmo** [comment]
v0.2.2-beta.1 is showing the tray badge count again. I don't notice any other issues. Seems to be good.

**Comment by YoungFellow-le** [comment]
> v0.2.2-beta.1 is showing the tray badge count again. I don't notice any other issues. Seems to be good.

Are you a WhatsApp beta tester?
