### ISSUE TITLE
[Bug Report] The WALC settings icon is missing after WhatsApp update

### ISSUE THREAD

**Issue by MisconceivedSec** [WAClient/WALC#158]
**Describe the bug**
Ever since the latest update WhatsApp released, the WALC settings icon is now missing

**WALC Installation Type:** AppImage / Snap
AppImage

**To Reproduce**
Steps to reproduce the behaviour:
1. Open WALC.
2. Log in to WhatsApp web.
4. Then you'll see that there is no icon at the top.

**Expected behaviour**
The icon should be available to change WALC's settings.

**Did you try closing and then opening it back?:**
Yes, multiple times.

**Screenshots**

![image](https://user-images.githubusercontent.com/79008923/125266701-83396480-e31f-11eb-94b8-aebb5fc49a5d.png)

**System Information (please complete the following information):**
- **Distro:** Linux Mint 20.1 Ulyssa
- **Desktop:** Cinnamon 4.8.6 
- **Kernel:** 5.4.0-66-generic x86_64

**Additional context**
Started after the last WhatsApp update.

**Comment by bkmo** [comment]
same with Arch KDE

**Comment by YoungFellow-le** [comment]
I believe that it's about time a new version of WALC is released, and a new logo should be chosen.
I will be working on one myself, and I would've loved to help in the development, but my field is in Java android apps.

**Comment by aliquo93** [comment]
I have the same problem on latest 0.2.2 version

**Comment by i-am-ecc** [comment]
It happened for me as well.

AppImage v0.3.1
Ubuntu 22.04 LTS

**Comment by MisconceivedSec** [comment]
Integration has been broken for a while now, but the settings panel was still accessible. Now it's gone completely.
Wait, I opened this PR?
I'll reopen it then.

**Comment by Zzombiee2361** [comment]
Should be fixed in latest version

**Comment by Sadi58** [comment]
Unfortunately, this problem is back again. :-(
