### ISSUE TITLE
[Bug Report] The WALC settings icon is missing

### ISSUE THREAD

**Issue by Negan30** [WAClient/WALC#162]
OS : Deepin 20.2.3
WALC settings is missing i can't access settings i can't put walc auto startup
or zoom chat or anything cause simply there no Settings

where i can access Settings again? 
![image](https://user-images.githubusercontent.com/58732067/132090244-20b55bbb-1351-4e40-ba7a-7c0e990d0944.png)

**Comment by Zzombiee2361** [comment]
Please try the beta version and see if there's any issue
https://github.com/WAClient/WALC/releases

**Comment by Negan30** [comment]
> Please try the beta version and see if there's any issue
> https://github.com/WAClient/WALC/releases

no luck. settings option not show up

**Comment by Zzombiee2361** [comment]
Could you try logging out and logging back in and post the terminal output here?

**Comment by Negan30** [comment]
![image](https://user-images.githubusercontent.com/58732067/133368278-cc953b19-dcb4-4691-b6d4-c6609f05907c.png)

SURE HERE. logged out and logged in. can't access settings

**Comment by Zzombiee2361** [comment]
I see you're using whatsapp web beta. Unfortunately I can't support the beta version of whatsapp web

**Comment by Zzombiee2361** [comment]
Try logging out from your phone. There's a similar issue to yours and they got out of beta testing of whatsapp by logging out from their phone.

**Comment by Negan30** [comment]
> Try logging out from your phone. There's a similar issue to yours and they got out of beta testing of whatsapp by logging out from their phone.

well thanks for support but i don't prefer go out of beta. cause with beta i can use whatsapp anytime without have my phone ON !

you can close this, have a good day

**Comment by YoungFellow-le** [comment]
These features do not work with the beta version.

**Comment by Zzombiee2361** [comment]
Well, you have to live with that for now then. In the future I might make the icon works even without whatsapp integration but with reduced feature.

**Comment by YoungFellow-le** [comment]
> Well, you have to live with that for now then. In the future I might make the icon works even without whatsapp integration but with reduced feature.

I understand, following up with WhatsApp's updates.
But for next update, can you add the icon tray message count with the beta version?
Thank you.

**Comment by Zzombiee2361** [comment]
@aliquo93 please try the latest version

**Comment by aliquo93** [comment]
> @aliquo93 please try the latest version

I'm already using the latest version, 0.2.2

**Comment by aliquo93** [comment]
> > @aliquo93 please try the latest version
> 
> I'm already using the latest version, 0.2.2

Nevermind, I saw now that there is a new update
