### ISSUE TITLE
Google Chrome Version Error

### ISSUE THREAD

**Issue by alkaphreak** [WAClient/WALC#165]
I activate de the whatsapp beta version for multi device in my android smartphone and when i connect to WALC, the app told to upgrade to Google Chrome 60+

**WALC Installation Type:** Snap

Description:	Ubuntu 20.04.3 LTS
Kernel:		5.11.0-34-generic

**Comment by Zzombiee2361** [comment]
We don't support beta version unfortunately

**Comment by alkaphreak** [comment]
I reverted to standard on my phone but WALC is still asking me to upgrade chrome.

**Comment by Zzombiee2361** [comment]
Log out the whatsapp web from your phone and please try the beta version of WALC at https://github.com/WAClient/WALC/releases/tag/v0.2.2-beta.0
