### ISSUE TITLE
No more settings

### ISSUE THREAD

**Issue by asarubbo** [WAClient/WALC#171]
Hello,

today I updated my walc to the head version and I have no more settings:

![Screenshot_20220303_090836](https://user-images.githubusercontent.com/4741819/156523158-c4c29744-9aa1-4431-8c45-6d9ad81185f3.png)

When I tap on the WALC icon I get:

![Screenshot_20220303_090929](https://user-images.githubusercontent.com/4741819/156523284-268298f6-4db3-4385-9e97-5ad9dec345c5.png)

What I'm supposed to do?

**Comment by Zzombiee2361** [comment]
Hi, please try the new beta version

**Comment by Zzombiee2361** [comment]
I'm closing this issue due to no response. Feel free to reply here if you still have the issue on the latest beta version

**Comment by aliquo93** [comment]
I have the same problem on latest 0.2.2 version
