### ISSUE TITLE
whatsapp service worker error when trying to connect with a chrome extension

### ISSUE THREAD

**Issue by asantech** [WAClient/WALC#173]
hi,
I have bought a chrome extenstion named "NetSee v.3.1", which connects to whatsapp and its service worker.
when the manifest.json file was v2 version and now that it is v3, the whatsapp service worker gives me the error below, after when the extension reloads the page.

Screenshots
![image](https://user-images.githubusercontent.com/50336897/162744160-11b30b06-63ae-4219-8f37-19e796c2be96.png)

what should I do to fix it?

i will send my files here so you could see the manifest.hson file. thank you

1. install the extension by load by package.
2. set the developer mode button to "on"
3. run the extension (by clicking the extension button on top right part of chrome browser menu bar and clicking the "NetSee" extension from the dropdown menu).
4. click "Open Whatsapp Web, to get started" button
5. then if you inspect the whatsapp web page, in the console tab, you will the arrow below in the img

Expected behavior
seeing no errors in the console.

Did you try closing and then opening it back?
Yes, even on both manifest versions

**Comment by Zzombiee2361** [comment]
I don't think this is related to WALC. This seems like whatsapp / extension issue
