### ISSUE TITLE
A JavaScript error occourred in the main process - after clicking on the update whatsapp link thingy

### ISSUE THREAD

**Issue by YoungFellow-le** [WAClient/WALC#177]
I just got this error after clicking on the Update WhatsApp link/button, and after it WALC is unusable until I quit it and launch it again. 

![Screenshot_20220418_165922](https://user-images.githubusercontent.com/79008923/163805244-04c595d1-49c9-417b-a71b-32015d4e3ca0.png)

![Screenshot_20220416_200637](https://user-images.githubusercontent.com/79008923/163680343-016c254f-bfe1-4f0a-89da-9a2aee907c63.png)

_Originally posted by @YoungFellow-le in https://github.com/WAClient/WALC/discussions/174#discussioncomment-2579076_

**Comment by Zzombiee2361** [comment]
Try the latest beta, see if that fixed the issue

**Comment by YoungFellow-le** [comment]
Fixed in the latest release.
