### ISSUE TITLE
Repeated historic @Messages in group chat 

### ISSUE THREAD

**Issue by michaelfswann** [WAClient/WALC#196]
**Describe the bug**
Had back and forth messages in group chat on my phone, non specific IE not @ messages, opened conversation in WALC (already running, conversation not open) to reply from computer, WALC was showing new @ messages which I had previously received and read. They were all from one participant who was not the person who was chatting at the time. It didn't pick any other people's message where they have @'ed me.

**WALC Installation Type:**  Snap

**To Reproduce**
Opened following shutdown & used saved credentials to log back in.

Follow description group chat with old @ message from third party new not at message from second part back and forth on phone while WALC open on pc on different conversation. Open conversation WALC.

**Expected behavior**
I did not expect to be shown historic and read @ Messages. That were previously not there in same session on PC.

**Did you try closing and then opening it back?:** / No

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04

**Additional context**

    Is this on a server? No
    Do you have multiple clients on the same IP? Potentially as proxy
    Are you using a proxy? Yes

**Comment by Zzombiee2361** [comment]
Hiya, I don't quite understand the problem. But before we go any further, I just want to let you know that the snap version is currently unmaintained. Please try the latest appimage version to see if the problem persist

**Comment by michaelfswann** [comment]
Hey ok will do, feel free to mark as solved for now will reopen if it occurs again :) thanks

**Comment by Zzombiee2361** [comment]
Let me know if it's still happening
