### ISSUE TITLE
[Bug Report] on windows

### ISSUE THREAD

**Issue by MesterPerfect** [WAClient/WALC#205]
Can I build it and run it on Windows?

**Comment by BenHerbst** [comment]
It is a Vue.js electron app afaik, so it should be possible, although you could get problems with the native stuff like tray icon, autostart, ...

**Comment by YoungFellow-le** [comment]
Why not download the official [WhatsApp desktop application for Windows](https://www.whatsapp.com/download//)?

**Comment by BenHerbst** [comment]
> Why not download the official [WhatsApp desktop application for Windows](https://www.whatsapp.com/download//)?

Its not open source

**Comment by MesterPerfect** [comment]
> Why not download the official [WhatsApp desktop application for Windows](https://www.whatsapp.com/download//)?

I think I will try to play it soon

**Comment by MesterPerfect** [comment]
> > Why not download the official [WhatsApp desktop application for Windows](https://www.whatsapp.com/download//)?
> 
> Its not open source, but its best for Windows but you dont get password protection etc.

right

**Comment by Zzombiee2361** [comment]
Ignoring the fact that we would need to rebrand the app, there is a feature that are native to linux and that's the notification system and quick reply. Currently I that's the only feature that are native, but I'm planning to add more like unread badge number in task bar. I also want to add more feature to the notification system

**Comment by YoungFellow-le** [comment]
> unread badge number in task bar.

Don't we already have that?
