### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by MrMathematician** [WAClient/WALC#234]
**Describe the bug**
WhatsApp on smartphone shows on Linked Devices that Google Chrome (Mac OS) is the linked device. This is unexpected since I use Arch Linux.

**WALC Installation Type:** Snap

**To Reproduce**
1. (On Arch Linux) $sudo snap install WALC.
2. open WALC.
3. Link your laptop with WhatsApp on phone using the QR code.
4. Open the Linked Devices on WhatsApp on phone.
5. Google Chrome (Mac OS) appears instead of Google Chrome (Linux).

**Expected behavior**
The Linked devices should show Google Chrome (Linux).

**Did you try closing and then opening it back?:** Yes 

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro: Arch Linux kernel 6.4.12-arch1-1 on Gnome 44.4 Wayland

**Additional context**

**Comment by Zzombiee2361** [comment]
Yeah this is intended, we use custom user agent to prevent whatsapp from showing update browser message.
