### ISSUE TITLE
Notifications and badge count stops working

### ISSUE THREAD

**Issue by dagmoller** [WAClient/WALC#235]
Notifications and badge count stops working again, version 0.3.2

**Comment by MisconceivedSec** [comment]
Integration has been broken again...

**Comment by wokawoka** [comment]
I experience the same issue

**Comment by fcortesjp** [comment]
does this issue refers to not seeing a count or an indicator that message was received and has not been read? 
this is available in another client but I'm not seeing it in my current install of WALC, was this ever something available in WALC and not seeing it could be considered a bug or should I make this a feature request to see if it can be included in a future version?

**Comment by Sadi58** [comment]
Same here since Sept.
In my case, **native notification/popup message appears**, but the icon tray no longer displays the usual badge count.
_WALC-0.3.2.AppImage
Debian Testing
KDE Plasma 5.27.9_

**Comment by Zzombiee2361** [comment]
Weird, it's definitely still working just fine for me. The message counter and native notification works perfectly fine

**Comment by daffamumtaz2361** [comment]
I have released a new version that hopefully fix this.

Let me know here if the issue persists

**Comment by major-mayer** [comment]
I also can't see any message counter on the WALC tray icon.
Native notifications seem to work tho.

Using:
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.6.26-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 6 × Intel® Core™ i5-8600K CPU @ 3.60GHz
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6800
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7B46
System Version: 1.0
```
